#!/bin/sh

set -eu

# shellcheck source=../common.sh
. "$USERLAND_ROOT/lib/common.sh"

userland_zsh_cache=$USERLAND_CACHE_DIR/zsh/init.zsh

userland_zsh_cache_fingerprint() {
  {
    userland_sha256 "$USERLAND_ROOT/lib/adapters/shell-cache.sh"
    userland_sha256 "$USERLAND_ROOT/completions/zsh"
    for userland_shell_command in atuin carapace direnv fzf starship zoxide; do
      if command -v "$userland_shell_command" >/dev/null 2>&1; then
        printf '%s\t%s\t' "$userland_shell_command" "$(command -v "$userland_shell_command")"
        "$userland_shell_command" --version 2>/dev/null | sed -n '1p'
      fi
    done
    if [ -n "${USERLAND_MISE:-}" ] && [ -x "$USERLAND_MISE" ]; then
      printf 'mise\t%s\t' "$USERLAND_MISE"
      "$USERLAND_MISE" --version 2>/dev/null | sed -n '1p'
      userland_pitchfork_path=$("$USERLAND_MISE" -C "$USERLAND_ROOT" which pitchfork 2>/dev/null || true)
      if [ -n "$userland_pitchfork_path" ] && [ -x "$userland_pitchfork_path" ]; then
        printf 'pitchfork\t%s\t' "$userland_pitchfork_path"
        "$userland_pitchfork_path" --version 2>/dev/null | sed -n '1p'
      fi
    fi
  } | shasum -a 256 | awk '{print $1}'
}

userland_zsh_cache_is_current() {
  [ -s "$userland_zsh_cache" ] || return 1
  userland_zsh_cache_expected=$(userland_zsh_cache_fingerprint)
  IFS= read -r userland_zsh_cache_header <"$userland_zsh_cache" || return 1
  [ "$userland_zsh_cache_header" = "# userland-shell-cache: $userland_zsh_cache_expected" ]
}

userland_generate_zsh_cache() {
  userland_mkdirs
  mkdir -p "$(dirname "$userland_zsh_cache")"
  userland_zsh_cache_tmp=$userland_zsh_cache.tmp.$$
  userland_zsh_cache_fingerprint_value=$(userland_zsh_cache_fingerprint)

  {
    printf '# userland-shell-cache: %s\n' "$userland_zsh_cache_fingerprint_value"
    printf '%s\n' '# Generated by userland sync. Do not edit.'
    printf '%s\n' "zstyle ':completion:*' format \$'\\e[2;37mCompleting %d\\e[m'"
    printf '%s\n' 'autoload -Uz compinit'
    printf '%s\n' '_userland_zcompdump=${XDG_CACHE_HOME:-$HOME/.cache}/userland/zsh/zcompdump'
    printf '%s\n' 'if [[ -r "$_userland_zcompdump" ]]; then'
    printf '%s\n' '  compinit -C -d "$_userland_zcompdump"'
    printf '%s\n' 'else'
    printf '%s\n' '  compinit -d "$_userland_zcompdump"'
    printf '%s\n' 'fi'
    printf '%s\n' 'unset _userland_zcompdump'
    "$USERLAND_ROOT/bin/userland" completions zsh

    if command -v atuin >/dev/null 2>&1; then atuin init zsh; fi
    if command -v carapace >/dev/null 2>&1; then carapace _carapace zsh; fi
    if command -v direnv >/dev/null 2>&1; then direnv hook zsh; fi
    if command -v fzf >/dev/null 2>&1; then fzf --zsh; fi
    if command -v starship >/dev/null 2>&1; then starship init zsh; fi
    if command -v zoxide >/dev/null 2>&1; then zoxide init zsh; fi
    if [ -n "${USERLAND_MISE:-}" ] && [ -x "$USERLAND_MISE" ]; then "$USERLAND_MISE" completion zsh; fi
    if [ -n "${USERLAND_MISE:-}" ] && [ -x "$USERLAND_MISE" ]; then
      userland_pitchfork_path=$("$USERLAND_MISE" -C "$USERLAND_ROOT" which pitchfork 2>/dev/null || true)
      if [ -n "$userland_pitchfork_path" ] && [ -x "$userland_pitchfork_path" ]; then
        "$userland_pitchfork_path" activate zsh
      fi
    fi
  } >"$userland_zsh_cache_tmp"

  mv "$userland_zsh_cache_tmp" "$userland_zsh_cache"
  userland_log changed "regenerated the static Zsh initialization cache"
}

case "${1:-}" in
  plan)
    if userland_zsh_cache_is_current; then
      userland_log current "static Zsh initialization cache is current"
    else
      userland_log change "static Zsh initialization cache will be generated"
    fi
    ;;
  apply)
    userland_generate_zsh_cache
    ;;
  doctor)
    if userland_zsh_cache_is_current; then
      userland_log healthy "static Zsh initialization cache is current"
    else
      userland_log attention "static Zsh initialization cache is missing or stale"
      exit 2
    fi
    ;;
  *)
    userland_die "shell-cache adapter expects plan, apply, or doctor" 64
    ;;
esac
