#!/bin/sh

set -eu

# shellcheck source=../common.sh
. "$USERLAND_ROOT/lib/common.sh"

userland_zsh_cache=$USERLAND_CACHE_DIR/zsh/init.zsh

userland_generate_zsh_cache() {
  userland_mkdirs
  mkdir -p "$(dirname "$userland_zsh_cache")"
  userland_zsh_cache_tmp=$userland_zsh_cache.tmp.$$

  {
    printf '%s\n' '# Generated by userland sync. Do not edit.'
    printf '%s\n' "zstyle ':completion:*' format \$'\\e[2;37mCompleting %d\\e[m'"

    if command -v atuin >/dev/null 2>&1; then atuin init zsh; fi
    if command -v carapace >/dev/null 2>&1; then carapace _carapace; fi
    if command -v direnv >/dev/null 2>&1; then direnv hook zsh; fi
    if command -v fzf >/dev/null 2>&1; then fzf --zsh; fi
    if command -v starship >/dev/null 2>&1; then starship init zsh; fi
    if command -v zoxide >/dev/null 2>&1; then zoxide init zsh; fi
    if [ -n "${USERLAND_MISE:-}" ] && [ -x "$USERLAND_MISE" ]; then "$USERLAND_MISE" completion zsh; fi
    if command -v pitchfork >/dev/null 2>&1; then pitchfork activate zsh; fi
  } >"$userland_zsh_cache_tmp"

  mv "$userland_zsh_cache_tmp" "$userland_zsh_cache"
  userland_log changed "regenerated the static Zsh initialization cache"
}

case "${1:-}" in
  plan)
    if [ -s "$userland_zsh_cache" ]; then
      userland_log current "static Zsh initialization cache exists"
    else
      userland_log change "static Zsh initialization cache will be generated"
    fi
    ;;
  apply)
    userland_generate_zsh_cache
    ;;
  doctor)
    if [ -s "$userland_zsh_cache" ]; then
      userland_log healthy "static Zsh initialization cache exists"
    else
      userland_log attention "static Zsh initialization cache is missing"
      exit 2
    fi
    ;;
  *)
    userland_die "shell-cache adapter expects plan, apply, or doctor" 64
    ;;
esac
