package adapters

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func shellCache(c *Context, action Action) int {
	path := filepath.Join(c.Env.Cache, "zsh", "init.zsh")
	fingerprint := ""
	current := false
	if contents, err := os.ReadFile(path); err == nil {
		fingerprint = shellFingerprint(c)
		current = firstLine(contents) == "# userland-shell-cache: "+fingerprint
	}
	if action == Plan {
		if current {
			c.Log(Current, "static Zsh initialization cache is current")
		} else {
			c.Log(Change, "static Zsh initialization cache will be generated")
		}
		return 0
	}
	if action == Doctor {
		if current {
			c.Log(Healthy, "static Zsh initialization cache is current")
			return 0
		}
		c.Log(Attention, "static Zsh initialization cache is missing or stale")
		return 2
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return 1
	}
	if fingerprint == "" {
		fingerprint = shellFingerprint(c)
	}
	var output bytes.Buffer
	fmt.Fprintf(&output, "# userland-shell-cache: %s\n", fingerprint)
	output.WriteString("# Generated by userland sync. Do not edit.\n")
	output.WriteString("zstyle ':completion:*' format $'\\e[2;37mCompleting %d\\e[m'\n")
	output.WriteString("autoload -Uz compinit\n")
	output.WriteString("_userland_zcompdump=${XDG_CACHE_HOME:-$HOME/.cache}/userland/zsh/zcompdump\n")
	output.WriteString("if [[ -r \"$_userland_zcompdump\" ]]; then\n")
	output.WriteString("  compinit -C -d \"$_userland_zcompdump\"\n")
	output.WriteString("else\n")
	output.WriteString("  compinit -d \"$_userland_zcompdump\"\n")
	output.WriteString("fi\n")
	output.WriteString("unset _userland_zcompdump\n")
	completion, err := os.ReadFile(filepath.Join(c.Env.Root, "completions", "zsh"))
	if err != nil {
		return 1
	}
	output.Write(completion)
	for _, command := range []struct {
		name string
		args []string
	}{
		{"atuin", []string{"init", "zsh"}}, {"carapace", []string{"_carapace", "zsh"}},
		{"direnv", []string{"hook", "zsh"}}, {"fzf", []string{"--zsh"}},
		{"starship", []string{"init", "zsh"}}, {"zoxide", []string{"init", "zsh"}},
	} {
		if path, ok := platformCommand(c, command.name); ok {
			result := run(c, path, command.args...)
			if result.Code != 0 {
				return result.Code
			}
			output.Write(result.Output)
		}
	}
	if executable(c.Env.Mise) {
		result := run(c, c.Env.Mise, "completion", "zsh")
		if result.Code != 0 {
			return result.Code
		}
		output.Write(result.Output)
		which := run(c, c.Env.Mise, "-C", c.Env.Root, "which", "pitchfork")
		pitchfork := firstLine(which.Output)
		if which.Code == 0 && executable(pitchfork) {
			result = run(c, pitchfork, "activate", "zsh")
			if result.Code != 0 {
				return result.Code
			}
			output.Write(result.Output)
		}
	}
	temporary := path + ".tmp"
	if err := os.WriteFile(temporary, output.Bytes(), 0o600); err != nil {
		return 1
	}
	if err := os.Rename(temporary, path); err != nil {
		return 1
	}
	c.Log(Changed, "regenerated the static Zsh initialization cache")
	return 0
}

func shellFingerprint(c *Context) string {
	hash := sha256.New()
	hash.Write([]byte("userland-shell-cache-v2\n"))
	if contents, err := os.ReadFile(filepath.Join(c.Env.Root, "completions", "zsh")); err == nil {
		hash.Write(contents)
	}
	for _, name := range []string{"atuin", "carapace", "direnv", "fzf", "starship", "zoxide"} {
		if path, ok := platformCommand(c, name); ok {
			result := run(c, path, "--version")
			fmt.Fprintf(hash, "%s\t%s\t%s\n", name, path, firstLine(result.Output))
		}
	}
	if executable(c.Env.Mise) {
		result := run(c, c.Env.Mise, "--version")
		fmt.Fprintf(hash, "mise\t%s\t%s\n", c.Env.Mise, firstLine(result.Output))
		which := run(c, c.Env.Mise, "-C", c.Env.Root, "which", "pitchfork")
		if path := firstLine(which.Output); which.Code == 0 && executable(path) {
			version := run(c, path, "--version")
			fmt.Fprintf(hash, "pitchfork\t%s\t%s\n", path, firstLine(version.Output))
		}
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func platformCommand(c *Context, name string) (string, bool) {
	path, ok := commandPath(c, "", name)
	return strings.TrimSpace(path), ok
}
