package adapters

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var shellEnvironmentName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

type miseShellEnvironment struct {
	BinPaths []string
	Values   map[string]string
}

func shellCache(c *Context, action Action) int {
	initPath := filepath.Join(c.Env.Cache, "zsh", "init.zsh")
	environmentPath := filepath.Join(c.Env.Cache, "zsh", "mise-env.zsh")
	if !exists(initPath) || !exists(environmentPath) {
		if action == Plan {
			c.Log(Change, "static Zsh initialization cache will be generated")
			return 0
		}
		if action == Doctor {
			c.Log(Attention, "static Zsh initialization cache is missing or stale")
			return 2
		}
	}
	environment, err := globalMiseEnvironment(c)
	if err != nil {
		c.Log(Attention, "static global tool environment could not be generated: "+err.Error())
		if action == Doctor {
			return 2
		}
		return 1
	}
	fingerprint := shellFingerprint(c, environment)
	current := shellCacheCurrent(initPath, fingerprint) && shellCacheCurrent(environmentPath, fingerprint)
	if action == Plan {
		if current {
			c.Log(Current, "static Zsh initialization cache is current")
		} else {
			c.Log(Change, "static Zsh initialization cache will be generated")
		}
		return 0
	}
	if action == Doctor {
		if current {
			c.Log(Healthy, "static Zsh initialization cache is current")
			return 0
		}
		c.Log(Attention, "static Zsh initialization cache is missing or stale")
		return 2
	}
	if err := os.MkdirAll(filepath.Dir(initPath), 0o755); err != nil {
		return 1
	}
	environmentContents := miseEnvironmentContents(fingerprint, environment)
	var output bytes.Buffer
	fmt.Fprintf(&output, "# userland-shell-cache: %s\n", fingerprint)
	output.WriteString("# Generated by userland sync. Do not edit.\n")
	output.WriteString("zstyle ':completion:*' format $'\\e[2;37mCompleting %d\\e[m'\n")
	output.WriteString("autoload -Uz compinit\n")
	output.WriteString("_userland_zcompdump=${XDG_CACHE_HOME:-$HOME/.cache}/userland/zsh/zcompdump\n")
	output.WriteString("if [[ -r \"$_userland_zcompdump\" ]]; then\n")
	output.WriteString("  compinit -C -d \"$_userland_zcompdump\"\n")
	output.WriteString("else\n")
	output.WriteString("  compinit -d \"$_userland_zcompdump\"\n")
	output.WriteString("fi\n")
	output.WriteString("unset _userland_zcompdump\n")
	completion, err := os.ReadFile(filepath.Join(c.Env.Root, "completions", "zsh"))
	if err != nil {
		return 1
	}
	output.Write(completion)
	for _, command := range []struct {
		name string
		args []string
	}{
		{"atuin", []string{"init", "zsh"}}, {"carapace", []string{"_carapace", "zsh"}},
		{"direnv", []string{"hook", "zsh"}}, {"fzf", []string{"--zsh"}},
		{"starship", []string{"init", "zsh"}}, {"zoxide", []string{"init", "zsh"}},
	} {
		if path, ok := platformCommand(c, command.name); ok {
			result := run(c, path, command.args...)
			if result.Code != 0 {
				return result.Code
			}
			output.Write(result.Output)
		}
	}
	if executable(c.Env.Mise) {
		result := run(c, c.Env.Mise, "completion", "zsh")
		if result.Code != 0 {
			return result.Code
		}
		output.Write(result.Output)
		which := runMise(c, "which", "pitchfork")
		pitchfork := firstLine(which.Output)
		if which.Code == 0 && executable(pitchfork) {
			result = run(c, pitchfork, "activate", "zsh")
			if result.Code != 0 {
				return result.Code
			}
			output.Write(result.Output)
		}
	}
	if err := writeShellCache(environmentPath, environmentContents); err != nil {
		return 1
	}
	if err := writeShellCache(initPath, output.Bytes()); err != nil {
		return 1
	}
	c.Log(Changed, "regenerated the static Zsh initialization cache")
	return 0
}

func shellFingerprint(c *Context, environment miseShellEnvironment) string {
	hash := sha256.New()
	hash.Write([]byte("userland-shell-cache-v3\n"))
	for _, path := range environment.BinPaths {
		fmt.Fprintf(hash, "path\t%s\n", path)
	}
	keys := make([]string, 0, len(environment.Values))
	for key := range environment.Values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(hash, "env\t%s\t%s\n", key, environment.Values[key])
	}
	if contents, err := os.ReadFile(filepath.Join(c.Env.Root, "completions", "zsh")); err == nil {
		hash.Write(contents)
	}
	for _, name := range []string{"atuin", "carapace", "direnv", "fzf", "starship", "zoxide"} {
		if path, ok := platformCommand(c, name); ok {
			result := run(c, path, "--version")
			fmt.Fprintf(hash, "%s\t%s\t%s\n", name, path, firstLine(result.Output))
		}
	}
	if executable(c.Env.Mise) {
		result := runMise(c, "--version")
		fmt.Fprintf(hash, "mise\t%s\t%s\n", c.Env.Mise, firstLine(result.Output))
		which := runMise(c, "which", "pitchfork")
		if path := firstLine(which.Output); which.Code == 0 && executable(path) {
			version := run(c, path, "--version")
			fmt.Fprintf(hash, "pitchfork\t%s\t%s\n", path, firstLine(version.Output))
		}
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func shellCacheCurrent(path, fingerprint string) bool {
	contents, err := os.ReadFile(path)
	return err == nil && firstLine(contents) == "# userland-shell-cache: "+fingerprint
}

func writeShellCache(path string, contents []byte) error {
	temporary := path + ".tmp"
	if err := os.WriteFile(temporary, contents, 0o600); err != nil {
		return err
	}
	return os.Rename(temporary, path)
}

func globalMiseEnvironment(c *Context) (miseShellEnvironment, error) {
	binPaths, err := miseBinPaths(c)
	if err != nil {
		return miseShellEnvironment{}, err
	}
	result := runMise(c, "env", "--json")
	if result.Code != 0 {
		return miseShellEnvironment{}, fmt.Errorf("mise env failed: %s", strings.TrimSpace(string(result.Output)))
	}
	values := make(map[string]string)
	if err := json.Unmarshal(result.Output, &values); err != nil {
		return miseShellEnvironment{}, fmt.Errorf("mise env returned invalid JSON: %w", err)
	}
	delete(values, "PATH")
	for key := range values {
		if !shellEnvironmentName.MatchString(key) {
			return miseShellEnvironment{}, fmt.Errorf("mise env returned invalid variable name %q", key)
		}
	}
	return miseShellEnvironment{BinPaths: binPaths, Values: values}, nil
}

func miseBinPaths(c *Context) ([]string, error) {
	result := runMise(c, "bin-paths")
	if result.Code != 0 {
		return nil, fmt.Errorf("mise bin-paths failed: %s", strings.TrimSpace(string(result.Output)))
	}
	seen := make(map[string]bool)
	var paths []string
	for _, line := range strings.Split(string(result.Output), "\n") {
		path := strings.TrimSpace(line)
		if path == "" {
			continue
		}
		if !filepath.IsAbs(path) {
			return nil, fmt.Errorf("mise bin-paths returned non-absolute path %q", path)
		}
		if !seen[path] {
			seen[path] = true
			paths = append(paths, path)
		}
	}
	return paths, nil
}

func miseEnvironmentContents(fingerprint string, environment miseShellEnvironment) []byte {
	var output bytes.Buffer
	fmt.Fprintf(&output, "# userland-shell-cache: %s\n", fingerprint)
	output.WriteString("# Generated by userland sync. Do not edit.\n")
	keys := make([]string, 0, len(environment.Values))
	for key := range environment.Values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(&output, "export %s=%s\n", key, zshQuote(environment.Values[key]))
	}
	output.WriteString("typeset -gU path PATH\npath=(\n")
	for _, path := range environment.BinPaths {
		fmt.Fprintf(&output, "  %s\n", zshQuote(path))
	}
	output.WriteString("  $path\n)\nexport PATH\n")
	return output.Bytes()
}

func zshQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func platformCommand(c *Context, name string) (string, bool) {
	path, ok := commandPath(c, "", name)
	return strings.TrimSpace(path), ok
}
